### ISSUE TITLE
Bad incoming Lat/Lon data

### ISSUE THREAD

**Issue by dmullis** [simonw/ca-fires-history#1]
Happened on this:

`  $ git-log -G '["]Longitude["]: -1[0-9][0-9][0-9]' --patch | grep -e 'Latest data:' -e '["]Longitude["]: -1[0-9][0-9][0-9]'`

        Latest data: Mon Apr 26 12:10:42 UTC 2021
    +      "Longitude": -1191414610,
        Latest data: Mon Apr 26 11:49:03 UTC 2021
    -      "Longitude": -1191414610,
        Latest data: Sat Apr 24 20:49:11 UTC 2021
    +      "Longitude": -1191414610,
        Latest data: Sat Apr 24 15:10:14 UTC 2021
    -      "Longitude": -1191414610,
        Latest data: Fri Apr 23 01:11:43 UTC 2021
    -      "Longitude": -1191414610,
    -      "Longitude": -1191414610,
           "Longitude": -1191414610,
        Latest data: Fri Apr 23 00:43:07 UTC 2021
    +      "Longitude": -1191414610,
    +      "Longitude": -1191414610,
    +      "Longitude": -1191414610,

Note missing decimal point.

**Comment by simonw** [comment]
Obsolete now, thanks to #5
