### ISSUE TITLE
Exclude AllYearIncidents.UpdatedDate

### ISSUE THREAD

**Issue by blitmap** [simonw/ca-fires-history#3]
Hello,

Regularly the only change in the .json is the AllYearIncidents.UpdatedDate.  When I forked this project for another purpose, I was seeing thousands of commits for a similar "rundate" member on the JSON I was watching for changes.  Looks like you can have jq remove/exclude that member:  `| jq 'del(.AllYearIncidents.UpdatedDate)' ...` in scrape.yml

I thought I'd pass it along if that's useful to you :-)

Cheers ~

**Comment by simonw** [comment]
Obsolete now, thanks to https://github.com/simonw/ca-fires-history/issues/5
